name: Release PR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: release-pr
  cancel-in-progress: false

jobs:
  prepare:
    uses: civitaspo/securefix-server/.github/workflows/reusable-release-pr.yml@ccb564da7e61d22e1718aecc85af05ac43383249
    secrets:
      SECUREFIX_CLIENT_PRIVATE_KEY: ${{ secrets.SECUREFIX_CLIENT_PRIVATE_KEY }}
