name: Release PR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: release-pr
  cancel-in-progress: false

jobs:
  prepare:
    uses: civitaspo/securefix-server/.github/workflows/reusable-release-pr.yml@f0cd60319a245bc10c474de01fce3d89f5317ca2 # f0cd603
    secrets:
      SECUREFIX_CLIENT_PRIVATE_KEY: ${{ secrets.SECUREFIX_CLIENT_PRIVATE_KEY }}
